### ISSUE TITLE
Unable to run my project due to unavailable dep

### ISSUE THREAD

**Issue by LoganTann** [eveningkid/denodb#348]
I tried to add `denodb` to my project, but a dependency seems unavailable.

`error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error`

![error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error](https://user-images.githubusercontent.com/28659185/174688454-69f91f99-93e6-439e-8789-0c1ad6e2e4ef.png)

## steps to reproduce

* make sure docker in installed in your system.
* clone the code in https://github.com/LoganTann/redbeansoup-v2/tree/issue-timerjs
* run the code by moving in the repo's root folder, and `docker-compose up`

**Comment by Aiko-Suzuki** [comment]
opened a quick pull request a 2w ago to address this issues.
#347

**Comment by LoganTann** [comment]
Yes, I use your repo as import URL since I opened this issue
I hope it will get merged soon !

**Comment by slim-hmidi** [comment]
@LoganTann @Aiko-Suzuki which version of deno you are using? because with the fix that @Aiko-Suzuki  did, I got these errors now:
```
error: TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:100:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
        // @ts-expect-error
        ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:105:9

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:116:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:200:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:225:5

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
        // @ts-expect-error
        ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:391:9

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:424:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
          // @ts-expect-error
          ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:446:11

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
          // @ts-expect-error
          ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:451:11

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:646:5

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.106.0/node/events.ts:667:5

TS2345 [ERROR]: Argument of type 'FieldValue' is not assignable to parameter of type 'string | number | Uint8Array | ObjectId | undefined'.
  Type 'null' is not assignable to type 'string | number | Uint8Array | ObjectId | undefined'.
          whereClause.value = new Bson.ObjectId(whereClause.value);
                                                ~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/Aiko-Suzuki/denodb/master/lib/connectors/mongodb-connector.ts:78:49

TS2345 [ERROR]: Argument of type 'FieldValue' is not assignable to parameter of type 'string | number | Uint8Array | ObjectId | undefined'.
              (value) => new Bson.ObjectId(value)
                                           ~~~~~
    at https://raw.githubusercontent.com/Aiko-Suzuki/denodb/master/lib/connectors/mongodb-connector.ts:152:44

Found 13 errors.
```
I'm using deno v1.21.3

**Comment by slim-hmidi** [comment]
it's clear, because even in the PR check there are the same log errors, you can check them https://github.com/eveningkid/denodb/pull/347/checks

**Comment by LoganTann** [comment]
> I'm using deno v1.21.3

1.22.1 in my side

**Comment by joeldesante** [comment]
Is there any progress on this issue? I see a pull request has been open but has not yet been merged.

**Comment by Aiko-Suzuki** [comment]
The maintainer seems to not be actif :/

**Comment by joeldesante** [comment]
I've implemented the pull request [on my own fork of the project](https://github.com/joeldesante/denodb) if anyone needs it and doesn't want to do it themselves.

Here is an example of the import to use the fixed version while we wait for the pull request.
```
import { Relationships, DataTypes, Database, Model, SQLite3Connector } from 'https://raw.githubusercontent.com/joeldesante/denodb/master/mod.ts';
```

**Comment by tutusmart** [comment]
I still don't quite understand how to deal with this problem
<img width="975" alt="image" src="https://user-images.githubusercontent.com/29091787/179501655-e6b74029-dc74-4138-b20e-d06e985b7fa5.png">

**Comment by LoganTann** [comment]
> I still don't quite understand how to deal with this problem <img alt="image" width="975" src="https://user-images.githubusercontent.com/29091787/179501655-e6b74029-dc74-4138-b20e-d06e985b7fa5.png">

Instead of `import {something} from "https://deno.land/x/denodb/mod.ts";`  
Do this instead : `import {something} from "https://raw.githubusercontent.com/joeldesante/denodb/master/mod.ts";`

**Comment by paulocr** [comment]
> I've implemented the pull request [on my own fork of the project](https://github.com/joeldesante/denodb) if anyone needs it and doesn't want to do it themselves.
> 
> Here is an example of the import to use for the fixed version while we wait for the pull request.
> 
> ```js
> import { Relationships, DataTypes, Database, Model, SQLite3Connector } from 'https://raw.githubusercontent.com/joeldesante/denodb/master/mod.ts';
> ```

There is a new error with your workaround (at least today):

```
Download https://raw.githubusercontent.com/Zhomart/dex/update-deps/lib/deps/tarn@3.0.0/dist/PromiseInspection.dew.js
error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error
    at https://dev.jspm.io/npm:tarn@3.0.2/dist/Pool.dew.js:5:21
```

**Comment by joeldesante** [comment]
> > I've implemented the pull request [on my own fork of the project](https://github.com/joeldesante/denodb) if anyone needs it and doesn't want to do it themselves.
> > Here is an example of the import to use for the fixed version while we wait for the pull request.
> > ```js
> > import { Relationships, DataTypes, Database, Model, SQLite3Connector } from 'https://raw.githubusercontent.com/joeldesante/denodb/master/mod.ts';
> > ```
> 
> There is a new error with your workaround (at least today):
> 
> ```
> Download https://raw.githubusercontent.com/Zhomart/dex/update-deps/lib/deps/tarn@3.0.0/dist/PromiseInspection.dew.js
> error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error
>     at https://dev.jspm.io/npm:tarn@3.0.2/dist/Pool.dew.js:5:21
> ```

I havn't been able to reproduce this error. Are you sure you have everything correct on your end?

**Comment by paulocr** [comment]
> > > I've implemented the pull request [on my own fork of the project](https://github.com/joeldesante/denodb) if anyone needs it and doesn't want to do it themselves.
> > > Here is an example of the import to use for the fixed version while we wait for the pull request.
> > > ```js
> > > import { Relationships, DataTypes, Database, Model, SQLite3Connector } from 'https://raw.githubusercontent.com/joeldesante/denodb/master/mod.ts';
> > > ```
> > 
> > 
> > There is a new error with your workaround (at least today):
> > ```
> > Download https://raw.githubusercontent.com/Zhomart/dex/update-deps/lib/deps/tarn@3.0.0/dist/PromiseInspection.dew.js
> > error: Import 'https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js' failed: 500 Internal Server Error
> >     at https://dev.jspm.io/npm:tarn@3.0.2/dist/Pool.dew.js:5:21
> > ```
> 
> I havn't been able to reproduce this error. Are you sure you have everything correct on your end?

Yes, sorry nevermind. I think I was missing something on my end. Thanks for the workaround!

**Comment by reggi** [comment]
Still seeing this:

```
error: Import 'https://dev.jspm.io/inherits@2.0' failed: 500 Internal Server Error
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:4:26
```

**Comment by reggi** [comment]
workaround:

```json
{
  "imports": {
    "https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/deno/timers.ts",
    "@jspm/core/nodelibs/timers": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/deno/timers.ts",
    "inherits": "https://ga.jspm.io/npm:inherits@2.0.4/inherits.js",
    "https://dev.jspm.io/inherits@2.0": "https://ga.jspm.io/npm:inherits@2.0.4/inherits.js",
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "util": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/deno/util.ts"
    }
  }
}
```

**Comment by shizhouhu** [comment]
> 

its work!

**Comment by SirWrexes** [comment]
> workaround:
> 
> ```json
> {
>   "imports": {
>     "https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/deno/timers.ts",
>     "https://dev.jspm.io/inherits@2.0": "https://ga.jspm.io/npm:inherits@2.0.4/inherits.js",
>   },
>   "scopes": {
>     "https://ga.jspm.io/": {
>       "util": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/deno/util.ts"
>     }
>   }
> }
> ```

Thanks for the fix but where do I put this ??
Writing it in a `deno.json` and running my code with `deno --config ./deno.json ...` doesn't fix it.

**Comment by reggi** [comment]
@SirWrexes the code block I put my previous comment goes into  a `import_map.json` file.

In the `deno.json` you then need to add `"importMap": "./import_map.json"`.
